### ISSUE TITLE
Feature Request: Response/Status Codes Differences and Detectors

### ISSUE THREAD

**Issue by raulsiles** [Quitten/Autorize#35]
Congratulations on the Autorize Burp extension!

May I suggest to also display the differences between the response codes (or status codes, such as 200, 302, 404, 401, 403...) associated to the original, modified and unauthorized responses in the results table, in the same way the lengths for these three  responses are currently displayed?

Similarly, I think it would be very useful to include in both the Enforcement Detector and the Detector Unauthenticated sections new options in the Type field to easily filter by the response code (in the same way you can currently filter by the response length)? E.g. Detect enforcement if the response code is 302 (rather than 200).

If any additional clarification is required, please, let me know.

**Comment by Quitten** [comment]
Sounds legit, I will try to find some time to do so, if you can create PR it would be great, if not, give me couple of weeks and it will be done :)

**Comment by Quitten** [comment]
Resolved via 93a56815759408d3dc61a3f8fb72a62b944702e8, can you please verify it is satisfying your needs and close the issue?

**Comment by raulsiles** [comment]
Sorry about the delay in my response and verification of the suggested changes...

On the one hand, I've seen commit https://github.com/Quitten/Autorize/commit/93a56815759408d3dc61a3f8fb72a62b944702e8 adds status codes filters for both the Enforcement Detector and the Detector Unauthenticated. The result table portion of this feature request is still missing (see the last paragraph of this comment).

While testing the new capabilities, it seems that the Detector Unauthenticated is not working as expected (while the Enforcement Detector is). When a new filter is added with "Status code equals: 302", the default "And" condition makes the filter to detect the responses as "Enforced!", even when their status code is 200 (and the response content is the same for the three responses). If the condition is changed to "Or" (the default is "And"), it seems to work as expected. Also, when the default "And" condition is set, it seems the tool also detects as "Enforced!" scenarios when a 302 is returned for the three responses (again, with the same contents).

![image](https://user-images.githubusercontent.com/5730357/64868135-0a8ff100-d63f-11e9-924d-0e575799076b.png)

If the above description is right, the best option would be to change the default condition to "Or", or to fix the behaviour even when the default condition is set to "And".

It would also be useful to provide information within the tool clarifying that, by default, Autorize considers a status code of 401 as "Enforced!", and as far as I know, it is not configurable. Potentially, with this new status code filtering capabilities, the best option would be to remove the built-in 401 detection and add it as a default status code filtering rule for both modified and unauthenticated.

On the other hand, it would be great to keep this issue open to implement the three new columns in the results table to show the status codes of the original, modified and unauthenticated responses.

**Comment by Quitten** [comment]
Regarding your last point, i opened the issue https://github.com/Quitten/Autorize/issues/39
The bug you described above fixed on 8bb5b31.
Thanks a lot!
Closed, let me know if you have any comments
